version: '3.3'

services:
  nginx:
    restart: always
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - public:/var/app/public
    depends_on:
      - node
  node:
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - app:/node
      - node_modules:/node/node_modules
      - dist:/node/dist
      - public:/node/dist/public

volumes:
  app:
  node_modules:
  dist:
  public:
